"""Adiciona campo data em Purchase

Revision ID: bdbfc51cb954
Revises: 2de92fea2934
Create Date: 2025-04-10 11:05:47.359297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbfc51cb954'
down_revision = '2de92fea2934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
